export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDER = 'GET_ORDER';
export const ORDERS_LOADING = 'ORDERS_LOADING';
export const TAKE_ORDER = 'TAKE_ORDER';
export const CANCEL_ORDER = 'CANCEL_ORDER';